### ISSUE TITLE
graceful reload: kong reload on a machine with reasonable traffic and a go plugin leads to DOS

### ISSUE THREAD

**Issue by diefans** [Kong/go-pdk#108]
I filed a bug report at https://github.com/Kong/kong/issues/8531 but I have the feeling, that this could also be an issue with the go PDK itself.

There is https://github.com/bettermarks/kong_8531 to reproduce this issue.

Thanks for your attention!

**Comment by gszr** [comment]
This has since been fixed - thank you for the detailed report in https://github.com/bettermarks/kong_8531

**Comment by gszr** [comment]
https://github.com/Kong/kong/pull/8923/files
