### ISSUE TITLE
kong.ServiceResponse.GetRawBody()  return error string field contains invalid UTF-8

### ISSUE THREAD

**Issue by Andrei-cloud** [Kong/go-pdk#110]
Trying to do JSON to SOAP and back transformation

Request  has not problem to GetRawBody()

However, in Response phase  calling kong.ServiceResponse.GetRawBody() always return an error 

string field contains invalid UTF-8

tested even with JSOn service like mockbin.org

go-pdk v 0.7.1
Kong 2.7.0 also tried 2.8.x same result

go v 1.18.1 
also tried with go v 1.13

**Comment by Andrei-cloud** [comment]
Actually the issue was due to compressed body in response it was coming as gzip compressed

**Comment by Andrei-cloud** [comment]
compressed body is not read into spring

**Comment by andromedarabbit** [comment]
https://github.com/Kong/go-pdk/issues/125 might be what you were looking for
