### ISSUE TITLE
Possible error loss in the pbserver.servePb 

### ISSUE THREAD

**Issue by upvest-mike** [Kong/go-pdk#120]
Hello!
Please take a look https://github.com/Kong/go-pdk/blob/afb86724925a784b8d89f291e2b64a28eabfed8d/server/pbserver.go#L24
It looks like when servePb(...) returns error  this error is not sent to kong proxy, but proxy has some logic according to errors. Please see here https://github.com/Kong/kong/blob/8920006b2400bbc8e2ba8d329d8b6babc11aaf21/kong/runloop/plugin_servers/mp_rpc.lua#L332

It leads to situation when go-pdk removes one of plugins instance https://github.com/Kong/go-pdk/blob/afb86724925a784b8d89f291e2b64a28eabfed8d/server/instance.go#L156 but kong proxy still thinks that instance is ok, because error  is not propagated to proxy when proxy asks for missing instance.
 
Thank you!

**Comment by upvest-mike** [comment]
Hello!
Is there any additional information I can provide to attract a little attention to  this issue?

**Comment by StarlightIbuki** [comment]
Hi. Thanks for reporting this. The Go PDK speaks protobuf to talk to the gateway, so the corresponding implementation should be in `pb_rpc.lua`.
And the error handling happens differently than it may look like. The gateway optimistically assumes the instance exists, and it only handles the error by asking for a new instance if that's not the case.

**Comment by gszr** [comment]
As @StarlightIbuki said, the protobuf implementation is in `pb_rpc.lua`. 

Please note that in order for us to act on an issue, it needs to contain at least the following:
- Kong logs
- Kong version
- go-pdk version
- sample repro steps with valid code

Please reopen the issue with the required info.

Thanks!
