### ISSUE TITLE
Test package only supports `GET` requests

### ISSUE THREAD

**Issue by syanukov** [Kong/go-pdk#124]
There is the `test.Validate` function that ensures that only `GET` methods are allowed.

It means, the following `test.Request` is considered to be invalid
```
env, err := test.New(t, test.Request{
			Method: "POST",
			Url:    "...",
			...
		})
```

Is it a mistake or is there a reason why no other HTTP methods are supported?

**Comment by syanukov** [comment]
I have just found the same question and there is already PR for that
https://github.com/Kong/go-pdk/pull/75/files#r661797816

**Comment by javierguerragiraldez** [comment]
> Looks like unfinished code

YAGNI

or, in other words, if there's a need now; now is the best time to write it, and not before.

as for #75 , probably it didn't align with the priorities at the time. (and doing different unrelated changes in the same one doesn't help).  again, should be easy to add if you feel something like that would be an improvement

**Comment by edualb** [comment]
Hello @javierguerragiraldez we have already two opened PRs to solve this issue:
- https://github.com/Kong/go-pdk/pull/75
- https://github.com/Kong/go-pdk/pull/156

Do you know when it can be merged?

**Comment by StarlightIbuki** [comment]
> Hello @javierguerragiraldez we have already two opened PRs to solve this issue:
> 
> * [add tests for test package #75](https://github.com/Kong/go-pdk/pull/75)
> * [[Fix] Support POST,PUT,PATCH & Fix Error when handle `kong.response.exit` #156](https://github.com/Kong/go-pdk/pull/156)
> 
> Do you know when it can be merged?

Thanks for reminding us. We will take a look soon.

**Comment by StarlightIbuki** [comment]
@156 is merged.
