### ISSUE TITLE
ExitArgs.Body should be `[]byte` instead of `string`

### ISSUE THREAD

**Issue by andromedarabbit** [Kong/go-pdk#125]
To handle gzipped body content, its type should be string or we would meet the encoding error like "string field contains invalid UTF-8". I have tried to modify the source files but the problem is here in `file_pluginsocket_proto_rawDesc`. 

`var file_pluginsocket_proto_rawDesc = []byte{ 
	0x0a, 0x12, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6b, 0x6f, 0x6e, 0x67, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f,
...
}` 

I suspect that `file_pluginsocket_proto_rawDesc` contains protobuf specs in binaries, right?

**Comment by cakemanny** [comment]
I saw https://github.com/Kong/go-pdk/pull/132 got merged, and it sounds like it fixes that you are describing, is that correct?

**Comment by gszr** [comment]
Closing this as resolved.
