### ISSUE TITLE
kong.ServiceResponse.GetRawBody() return empty string

### ISSUE THREAD

**Issue by BuiChiTrung** [Kong/go-pdk#139]
I am making a simple plugin to get the response from the upstream service & transform it before sending it back to the client as follow: 
```
type Config struct {
}

func New() interface{} {
	return &Config{}
}

func (config Config) Response(kong *pdk.PDK) {
	// The presence of the Response handler automatically enables the buffered proxy mode which allow using kong.ServiceResponse.GetRawBody()
}

func (config Config) Log(kong *pdk.PDK) {
	body, err := kong.ServiceResponse.GetRawBody()
	if err != nil {
		kong.Log.Err("error get service response: %v", err)
	}

	kong.Log.Debug("ahah")
	kong.Log.Debug(body)
	kong.Log.Debug("ahah")

	transformResponse(body)
}

func transformResponse(body string) {}

func main() {
	Version := "1.1"
	Priority := 1
	_ = server.StartServer(New, Version, Priority)
}
```

However, `kong.ServiceResponse.GetRawBody()` just return an empty string. Log result:
```
go-custom-plugin-kong-gateway-1   | 2023/02/18 03:36:50 [debug] 2194#0: *928 [kong] pb_rpc.lua:259 ahah
go-custom-plugin-kong-gateway-1   | 2023/02/18 03:36:50 [debug] 2194#0: *928 [kong] pb_rpc.lua:259 
go-custom-plugin-kong-gateway-1   | 2023/02/18 03:36:50 [debug] 2194#0: *928 [kong] pb_rpc.lua:259 ahah
```

Version:
+ go-pdk: 0.8.0
+ go: 1.19
+ kong docker image: kong/kong-gateway:3.1.1.3-alpine

Did I do anything wrong or this is a bug? Please help.

**Comment by BuiChiTrung** [comment]
`get_raw_body()` still works in a similar plugin written in Lua:
```
local HelloWorldHandler = {
    VERSION  = "1.0.0",
    PRIORITY = 10,
}

function HelloWorldHandler:access(conf)
    kong.service.request.enable_buffering()
end

function HelloWorldHandler:log(conf)
    kong.log("Hello world")
    kong.log(kong.service.response.get_raw_body())
    kong.log("Hello world")
end

return HelloWorldHandler
```

**Comment by BuiChiTrung** [comment]
It was my bad to use the postman with Accept-Encoding header to make the query. This header makes the response compressed which results in an empty string when binding Lua get_raw_body function to Go. Removing the header and the json response is printed out correctly.

**Comment by refaldyrk** [comment]
how your solved this problem?

**Comment by BuiChiTrung** [comment]
As I said, removed the Accept-Encoding header in the query.

**Comment by refaldyrk** [comment]
yes, i delete Accept-Encoding header in the query but original body from source i can't see, can i see you code?

fyi i wanna transform response body
