### ISSUE TITLE
Tag v_0.8.0 can't access kong.service.request.enable_buffering (method not found)

### ISSUE THREAD

**Issue by fnunezzz** [Kong/go-pdk#148]
I'm trying to access kong.service.request.enable_buffering method so I can access headers and body at the same time but it's not working in the latest tag. Per [Kong Docs](https://docs.konghq.com/gateway/latest/plugin-development/pdk/kong.service.request/) it's an available method. 

I decided to use a previous version (v_0.6.1) and the same method is present and working.

Here is a code example:

### v_0.8.0

```
func (conf Config) Access(kong *pdk.PDK) {
	err := kong.ServiceRequest.Ask("kong.service.request.enable_buffering", nil, nil)
	if (err != nil) {
		kong.Log.Err(err)
	} else {
		kong.Log.Notice("Enabling body and headers access")
	}
}
```
The following error happens: `method "kong.service.request.enable_buffering" not found`

I also tried the following implementation:

```
func (conf Config) Access(kong *pdk.PDK) {
        _, err := kong.ServiceRequest.AskString("kong.service.request.enable_buffering", nil)
	if (err != nil) {
		kong.Log.Err(err)
	} else {
		kong.Log.Notice("Enabling body and headers access")
	}
}
```

It's possible I am missing something but I couldn't figure it out.

### v_0.6.1 (working as intended)

```
func (conf Config) Access(kong *pdk.PDK) {
	_, err := kong.ServiceRequest.AskString("kong.service.request.enable_buffering", nil)
	if (err != nil) {
		kong.Log.Err(err)
	} else {
		kong.Log.Notice("Enabling body and headers access")
	}
}
```

**Comment by StarlightIbuki** [comment]
Currently `enable_buffering` is not supported for Go plugins.
Please referer to: https://pkg.go.dev/github.com/Kong/go-pdk

The correct way to call a PDK:

``` go
kong.ServiceRequest.SetMethod("GET")
```
