### ISSUE TITLE
kong.client.authenticate should support nil values for consumer and credential

### ISSUE THREAD

**Issue by lvermeire** [Kong/go-pdk#152]
https://github.com/Kong/go-pdk/blob/4deec45a5bfe421a0ceebcbf7931d395250949b0/client/client.go#L125-L152

The function kong.client.authenticate in the Kong PDK client module supports nil values for both consumer and credential: 

> While both `consumer` and `credential` can be `nil`, at least one of them must exist. Otherwise, this function will throw an error.

The current implementation of the go client does not allow either parameter to be nil, but it should.

**Comment by StarlightIbuki** [comment]
Thanks for the report and the PR! We will be looking into it soon.
