### ISSUE TITLE
kong.response.exit method not implemented

### ISSUE THREAD

**Issue by karuppiah7890** [Kong/go-pdk#16]
I'm talking about this method here - http://docs.konghq.com/1.4.x/pdk/kong.response/#kongresponseexitstatus-body-headers

I see a TODO here for the same in golang pdk

https://github.com/Kong/go-pdk/blob/b5672ac3fca7da76a2290a551fe308ef7388bb91/response/response.go#L60

I'm interested to analyze and raise a PR if that's okay. In any case, I'm going to try it out. If I back out at any point, I'll report back so that someone else can pick it up 😄

**Comment by karuppiah7890** [comment]
I got something working here 

https://github.com/karuppiah7890/go-pdk/blob/add-response-exit-method/response/response.go#L60-L63

**Comment by karuppiah7890** [comment]
I could raise a PR if that looks sane. I tried it out and it worked here - 

https://github.com/karuppiah7890/kong-plugin-kafka-upstream/blob/master/kafka_upstream.go#L13-L18

I can tell the rationale behind the implementation - it was mostly assumptions though 😅

**Comment by gszr** [comment]
@karuppiah7890 PRs are very welcome. Do note however that some PDK methods require special handling - serialization/deserialization mostly - so it's important to check how it works on the Lua side as well (in this case, `kong/pdk/response.lua`). Thank you for trying out the 2.0 rc1; we will go through all raised issues this week.

**Comment by karuppiah7890** [comment]
Closing as fixed in #22

**Comment by karuppiah7890** [comment]
Thanks to @javierguerragiraldez ! 😄
