### ISSUE TITLE
Question: Consumer Group Plugin

### ISSUE THREAD

**Issue by shunsukew** [Kong/go-pdk#166]
I'm planning to develop custom plugin for our usecase.
I assume currently only RateLimit plugin can be configurable for Consumer Group.

Is it technically possible to develop and apply Custom plugin for Consumer Group?
And is it planned to add plugin configuration other than Rate Limit to Consumer Group resource as official feature (e.g. via Kong Konnect Portal)?

**Comment by jschmid1** [comment]
Yes, `Consumer Groups` are now first-class entities, which means that you can scope plugins to it. Please check https://docs.konghq.com/gateway/latest/kong-enterprise/consumer-groups/ for more details.

If you plan to develop your own custom plugin, you can use this. (Note that Consumer Groups are an Enterprise feature)

**Comment by shunsukew** [comment]
I see, that's good to hear.
Thank you so much!
