### ISSUE TITLE
How can I share a Golang object between different phases quickly?

### ISSUE THREAD

**Issue by 007slm** [Kong/go-pdk#167]
I am developing a rate limiting plugin in Golang. In the plugin's logic, I need to generate a rate limiting object that is related to the current request URL during the access phase for QPS calculation. Then, in the response phase, I need to access this request-specific rate limiting object for further computation. How should I share this object between the two phases?

**Comment by gszr** [comment]
We encourage questions like this in the Discussions forum in the main Kong repo: https://github.com/Kong/kong/discussions.
