### ISSUE TITLE
How can i use custom golang plugin on kong ingress controller?

### ISSUE THREAD

**Issue by snxq** [Kong/go-pdk#203]
I wrote a plugin using go-pdk and tested it successfully in docker. However I couldn't find any documentation about deploying it on the Kong Ingress Controller.Is it supported?

**Comment by pteric** [comment]
fyi: https://dev.to/mfbmina/writing-kong-plugins-with-go-1h12

**Comment by snxq** [comment]
Sorry. I forgot this issue. Although I didn't find any documentation about deployment, I tried to deploy and successfully did so.
