### ISSUE TITLE
go-pdk v0.3.0 is missing kong.response.Exit method

### ISSUE THREAD

**Issue by aldor007** [Kong/go-pdk#25]
Hi
I'm trying to develop go plugin for kong, I'm using go mod for dependency management by default it is using a latest tag from go-pdk which is v0.3.0,  but this tag is missing kong.response.Exit. 

https://github.com/Kong/go-pdk/compare/v0.3.0...master 

When a new release of go-pdk will be released? 

PS Yes, I know that I can use the git hash.

**Comment by mfeledyn** [comment]
Hi @aldor007 
I have used go-pdk for a few days now I there is a kong.Response.Exit(...) function.
See here : https://godoc.org/github.com/Kong/go-pdk/response#Response

**Comment by aldor007** [comment]
Hi @mfeledyn 
Yes, I know that in master there is this method. I'm talking about tagged release
https://github.com/Kong/go-pdk/blob/v0.3.0/response/response.go

The default behavior of go mod is to use the latest tag which is not in sync with the master 

This issue can be simply fixed by adding a new tag to this repo.

**Comment by vnktram** [comment]
+1 for a new release. it would be great if we can release `go-pdk` with it's latest changes.

**Comment by aldor007** [comment]
@javierguerragiraldez any chance of new release?

**Comment by shreyu86** [comment]
In the same boat, would there be a new release?

**Comment by kuafou** [comment]
want a new release too !

**Comment by gszr** [comment]
Hi all, our apologies for the delay on our end. v0.3.1 has just been released!
