### ISSUE TITLE
Can it be applied to the production environment?

### ISSUE THREAD

**Issue by stevengao1995** [Kong/go-pdk#26]
Can it be applied to the production environment?

**Comment by irfn** [comment]
Would like to hear this as well

**Comment by mfeledyn** [comment]
Excellent question, I'd like to know about that.

**Comment by ealogar** [comment]
https://github.com/Kong/go-pluginserver/issues/21

**Comment by gszr** [comment]
Hi all. Go plugins were added as part of our recent 2.0 release; as such, there may still be some rough edges. That said, we have received some positive reports from users, and we are doing our best to fix issues and merge community contributions in a timely manner. If you find any issues, please feel free to report. Our next release will contain @ealogar's fix linked above; if you'd like to give it a try, it is in Kong's master branch.
