### ISSUE TITLE
TODO get_body

### ISSUE THREAD

**Issue by wenzhenxi** [Kong/go-pdk#29]
![image](https://user-images.githubusercontent.com/12265719/78206342-27075400-74d1-11ea-94bb-9794be126a2d.png)

**Comment by gszr** [comment]
@wenzhenxi Have you checked the `GetRawBody` [method](https://pkg.go.dev/github.com/Kong/go-pdk/request?tab=doc#Request.GetRawBody)? `GetBody` is indeed in our TODO list.

**Comment by pengdafu** [comment]
When is this method going to be added？

**Comment by gszr** [comment]
@pengdafu - we don't have a timeline. Have you tried the `GetRawBody` method (linked above) instead?

**Comment by pengdafu** [comment]
Thanks, I am currently using the getRawBody method, but when the body is too large, an error will confuse me.

**Comment by gszr** [comment]
@pengdafu could you open a new issue with the error you get when using `GetRawBody`? We will be glad to look into it. Thanks!

**Comment by gaolijuan** [comment]
I have the same problem

**Comment by javierguerragiraldez** [comment]
Given the RPC overhead between Kong and Go, it's much better to use `GetRawBody()` and use Go-native tools to split into request/headers/body.
