### ISSUE TITLE
How to persist user data

### ISSUE THREAD

**Issue by kev1n11** [Kong/go-pdk#31]
Ive noticed that the session plugin uses `kong.db` for storage yet this does not seem to be supported in Golang. Is this supported or is there another mechanism?

Context: we are migrating user credentials out of a monolith so during the migration period, we would like to support both session types and hence might need to write our custom plugin for that.

**Comment by kev1n11** [comment]
@javierguerragiraldez & @gszr you two are the main contributors, any thoughts here?

**Comment by javierguerragiraldez** [comment]
one of the goals of the Go plugin is to tap into the golang ecosystem, you can use any go package to manage persistence, databases, communications, etc.

we could add kong.db to go-pdk, bug given that the main performance bottleneck is the IPC channel between kong and go-pluginserver, it probably wouldn't be the best solution.

**Comment by gszr** [comment]
As @javierguerragiraldez points out, while the go-pdk doesn't expose `kong.db`, you can use any existing Go library for database connectivity. @kev1n11 do you have any other questions?

**Comment by SamuelTJackson** [comment]
Hey,
is it possible to use [cache](https://docs.konghq.com/2.1.x/plugin-development/entities-cache/)? _kong.cache_ is not available.

**Comment by kev1n11** [comment]
No further questions from me. Happy to close
