### ISSUE TITLE
how to set kong.ctx?

### ISSUE THREAD

**Issue by fangchih** [Kong/go-pdk#32]
There only getXXX methods in`kong/db/dao/plugins/go.lua` and `bridge.go`,  can I have a way to set kong.ctx in go plugin?

**Comment by gszr** [comment]
Hi @fangchih - Please checkout the PR I linked; it exposes both the Nginx request context and Kong's `kong.ctx` module (which provides `kong.ctx.plugin` and `kong.ctx.shared`). It will be included in the 2.1 release!

**Comment by fangchih** [comment]
cool!  thanks a lot.
