### ISSUE TITLE
How can i get the response header?

### ISSUE THREAD

**Issue by zhigangfang** [Kong/go-pdk#34]
Hello ~~~
kong.Response.GetHeader can not work in access phase, and go-pdk do not support header_filter and body_filter phase. so, how can i get the response header?

**Comment by ifree321** [comment]
I have the same needs, Because we don't know when where this pr merged and  this function is very urgent, We have to use Lua plugin to achieve this function

**Comment by fffonion** [comment]
This is now possible with the `Response` phase. Please re-open if you have more question.
