### ISSUE TITLE
Question: How I can find the logs printed by kong.Log.Notice()

### ISSUE THREAD

**Issue by westwin** [Kong/go-pdk#39]
I'm trying to debug my go-plugin by printing some debug logs with kong.Log

However, I don't know where to find the printed logs ?

I'm running kong with alpine docker image, and the logs I printed are not shown from stdout/stderr.

And where I can find the debug logs of go-pluginserver, I had an issue that sometimes my go-plugin stops to work, looks like Access() is not called. I'm trying to figure out why..

Any idea ?

**Comment by r3dsm0k3** [comment]
Did you try setting the `KONG_LOG_LEVEL` environment variable to `debug`?

**Comment by westwin** [comment]
> Did you try setting the `KONG_LOG_LEVEL` environment variable to `debug`?

thans, good to know.
