### ISSUE TITLE
kong.ServiceRequest.SetPath function seems not work... :(

### ISSUE THREAD

**Issue by zhyshen** [Kong/go-pdk#41]
I tried to rewrite the path of request but not successful.
raw path: /gameplatform_game.aaaa/aaaa   ---rewrite-->  /bbbb
![image](https://user-images.githubusercontent.com/3462903/86107103-006ab080-baf4-11ea-9600-78d5f5a5e8d5.png)
![image](https://user-images.githubusercontent.com/3462903/86107199-1c6e5200-baf4-11ea-9646-d3b5ad7cfac0.png)

any idea? thanks.

**Comment by fffonion** [comment]
@zhyshen `ServiceRequest` modifies attribute regarding a `Service` (or say "upstream" in Nginx term), while`Request` targets to the client request. So `kong.ServiceRequest.SetPath` call modifies the request URI kong sends to upstream, while `kong.Request.GetPath` returns the request URI your client sends to Kong, the later is unchanged as expected.

For more information please check out the PDK document https://docs.konghq.com/gateway-oss/2.3.x/pdk/kong.service.request/ and https://docs.konghq.com/gateway-oss/2.3.x/pdk/kong.request/
