### ISSUE TITLE
nowhere to set plugin priority

### ISSUE THREAD

**Issue by albertforweb** [Kong/go-pdk#42]
the Lua plugin priority can be set as (see https://docs.konghq.com/2.1.x/plugin-development/custom-logic/) :

CustomHandler.PRIORITY=10
 

but in go-pdk , i don't find a place to set the priority.

**Comment by comradedraganov** [comment]
Had to dig around through source code for this and although I can't find it documented anywhere it's possible to set it - https://github.com/Kong/go-pluginserver/blob/a443f0493c4250ae4919a7b0bfe3a97aeb662fb4/pluginserver.go#L262

You'd need to specify an exported Priority var in your plugin with the desired value.

**Comment by fffonion** [comment]
document added with https://github.com/Kong/docs.konghq.com/pull/2690

**Comment by fffonion** [comment]
Closing this as the docs is now added.
