### ISSUE TITLE
kong.Router.GetRoute() returns  error "expected type: entities.Route"

### ISSUE THREAD

**Issue by albertforweb** [Kong/go-pdk#45]
i am using kong 2.1.0 , and try to get current request route as below:

func getRoute(kong *pdk.PDK) (string, error) {
	var routeObj, routeErr = kong.Router.GetRoute()
	if routeErr != nil {
		var msg = fmt.Sprintf("unable to get current request route , error : %v", routeErr)
		logger(msg)
		return "", errors.New(msg)
	}
     
     ....
}

but see lots errors like this:

2020/08/07 21:57:11 [debug] 37#0: *1851 [kong] go.lua:352 unable to get current request route , error : **expected type: entities.Route**

What caused this ? 
How to fix or workaround ?

**Comment by javierguerragiraldez** [comment]
Hi @albertforweb, I'm trying to reproduce this issue.  It seems like the route object from Kong is missing some fields; maybe we can make them optional in the Go side.  What is the context of this function call? i.e. which event handler, the plugin configuration, which other plugins might also be running, etc.

**Comment by javierguerragiraldez** [comment]
Closing for lack of feedback.  Feel free to reopen if the issue still exists.
