### ISSUE TITLE
go-plugin can't get ctx set by lua

### ISSUE THREAD

**Issue by two** [Kong/go-pdk#47]
lua plugin at `body_filter` phase:
```lua
local function status()
        local s = kong.response.get_status()
        kong.ctx.shared.status = s
end
```
go plugin at `log` phase:
```go
func (conf Config) Log(kong *pdk.PDK) {

        status, err := kong.Ctx.GetSharedInt("status")
        if err!= nil {
                kong.Log.Err(err.Error())
        }
       ....
}
```
got error : `null response`

**Comment by PFadel** [comment]
Same error here, any response about this ?

**Comment by fffonion** [comment]
I can't reproduce the issue locally, which version of Kong and pluginserver are you using?

**Comment by javierguerragiraldez** [comment]
There have been several fixes and refactors around this code.  Closing for now as I don't think it's about a recent version, please reopen if the issue still exists.
