### ISSUE TITLE
Exposing prometheus metrics from a plugin

### ISSUE THREAD

**Issue by Symbianx** [Kong/go-pdk#48]
Hello,

We're using kong with custom plugins written in go to handle our authentication logic. 
We would like to monitor these plugins by exposing metrics in the prometheus plugin (we already have the prometheus plugin in place).
I noticed that the prometheus plugin now exposes the internal prometheus object. [Relevant PR here.](https://github.com/Kong/kong-plugin-prometheus/pull/78)
I was wondering if there's any way to access this prometheus object from within golang plugins to create our custom metrics.

Thank you.

**Comment by javierguerragiraldez** [comment]
There are methods to share data between plugins, but they need coordination at both sides.
