### ISSUE TITLE
How to use Kong cache?

### ISSUE THREAD

**Issue by cyrilgdn** [Kong/go-pdk#51]
I've opened a question on [Kong forum](https://discuss.konghq.com/t/using-kong-cache-in-go-plugins/7053) but as I didn't get any answer I allow myself to ask the question here.

We wrote a custom plugins in Go (an enhance version of [the JWT plugin](https://github.com/Kong/kong/tree/master/kong/plugins/jwt))thanks to this new `go-pdk` but we quickly faced performances problems.

In the plugin, we need to load consumers with the [`LoadConsumer`](https://github.com/Kong/go-pdk/blob/master/client/client.go#L103-L111) which basically calls the [`load_consumer`](https://docs.konghq.com/2.2.x/pdk/kong.client/#kongclientload_consumerconsumer_id-search_by_username) Lua function.
The documentation of this function says:

> Returns the consumer from the datastore (or cache).

But it seems that the cache is not managed by the function actually, so every call will trigger a select in the datastore (in our case Cassandra) which leads to dramatic performances.

We saw that every plugins has to write something like [that](https://github.com/Kong/kong/blob/master/kong/plugins/jwt/handler.lua#L210-L216):

```lua
  local consumer_cache_key = kong.db.consumers:cache_key(jwt_secret.consumer.id)
  local consumer, err      = kong.cache:get(consumer_cache_key, nil,
                                            kong.client.load_consumer,
                                            jwt_secret.consumer.id, true)
```

But I didn't find how to use the cache with the `go-pdk`.

So my questions are:

* Is there a way to use Kong cache in Go plugins.
* Or is it possible for the Lua client to expose functions that manage the cache for main entities (e.g.: `load_consumer_with_cache`).

Thanks in advance for your help.

**Comment by fffonion** [comment]
@cyrilgdn The PDK function indeed bypasses cache. I believe the comment might be pointing to the behaviour when you are using dbless mode.
Usually it will make sense to design a cache as close as possible to your logic, in this case it should live inside Go. You will still be able to access kong "cache" by calling `kong.Ctx.SetShared`/`kong.Ctx.GetShared`, but do note each PDK function involves heavy network operations and serializaion/deserialization. I would strongly recommend to not use kong's cache for this purpose.

**Comment by javierguerragiraldez** [comment]
closing this because lack of feedback from the original poster
