### ISSUE TITLE
no phase in kong.ctx.core.phase

### ISSUE THREAD

**Issue by chenjinxuan** [Kong/go-pdk#61]
![log](https://user-images.githubusercontent.com/25172225/114315192-531bd300-9b30-11eb-8c32-b14600e24a67.jpg)
![phase](https://user-images.githubusercontent.com/25172225/114315229-91b18d80-9b30-11eb-8d58-87b4872b0e17.jpg)
In the log phase, it cannot be used kong.Response.GetStatus () and kong.Router.GetService (),

**Comment by javierguerragiraldez** [comment]
Thanks for the report.  Because of a low-level limitation, Go plugins run the Log method after the nginx request/response object has been released, so each PDK function that requires information has to be handled as a special case.  It seems we missed `kong.Response.GetStatus()`
