### ISSUE TITLE
go-pluginserver is broken with the last commit

### ISSUE THREAD

**Issue by ealogar** [Kong/go-pdk#62]
A change was introduced in the pdk.Init interface and the go-pluginserver fails to be built:
```
#18 35.78 # github.com/Kong/go-pluginserver
#18 35.78 src/github.com/Kong/go-pluginserver/event.go:49:21: cannot use ipc (type chan interface {}) as type net.Conn in argument to pdk.Init:
#18 35.78 	chan interface {} does not implement net.Conn (missing Close method)
------
executor failed running [/bin/sh -c go get github.com/Kong/go-pluginserver]: exit code: 2
```

**Comment by ealogar** [comment]
I have introduced this issue https://github.com/Kong/docker-kong/issues/458 ... 
It would be nice than the changed in gopdk, pluginserver, etc were resolved in the kong deliverables as you can fix things like this quickier

**Comment by javierguerragiraldez** [comment]
as mentioned in Kong/docker-kong#458, go-pdk v0.7.0-beta1 isn't compatible with the go-pluginserver.  Using Go modules is the easiest way to avoid prerelease libraries

**Comment by ealogar** [comment]
I confirmed that what @javierguerragiraldez  suggests is the best way, you can close this issue
