### ISSUE TITLE
about get header error

### ISSUE THREAD

**Issue by ABNER-1** [Kong/go-pdk#67]
When I request with  a header such as `A_SESSION`, I fail to use GetHeader function to extrace `A_SESSION`. 
I finally successfully get header by key `a_session`.

I noticed document said that `Header names in are case-insensitive and are normalized to lowercase, and dashes (-) can be written as underscores (_); that is, the header X-Custom-Header can also be retrieved as x_custom_header.` 
However, it is Inconsistent with the experimental results.

Thanks for such good open source tools.

**Comment by ABNER-1** [comment]
My pdk is 0.5.0, and my go-plugin-server is 0.5.1

**Comment by javierguerragiraldez** [comment]
Thanks for the report.  Can you clarify if your code calls `GetHeader()` on the `Log()` handler?  I think it's related to the way we have to "preserve" request-related information.

**Comment by ABNER-1** [comment]
I get this error in `Access` phase.

**Comment by javierguerragiraldez** [comment]
I've verified that this was fixed in go-pdk 0.6.0

Sorry for the delay
