### ISSUE TITLE
Feature request: plugin instance lifecycle hooks

### ISSUE THREAD

**Issue by renato-zannon** [Kong/go-pdk#78]
Currently, I don't think there's a simple way to perform expensive initialization steps that depend on each plugin instance `Config` attributes.

For instance, I'm currently working on a (private) plugin that has a `parameter_name` config setting, which refers to AWS SSM Parameter Store. This value is relatively stable, can be cached for long periods, and is needed on my `Access` implementation.

Currently, I have to do something along these lines:
```golang
type Config struct {
    ParameterName `json:"parameter_name"`
    parameterValueInit sync.Once
    parameterValue string
}

func (c *Config) Access(kong *pdk.Pdk) {
  c.parameterValueInit.Do(func() {
    c.parameterValue = actuallyGetParameter(c.ParameterName)
  })

  // actually use c.parameterValue
}
```
Which means that the first request per plugin instance is burdened with this extra latency.

At first glance, the plugin constructor function would be the place for this kind of expensive shared initialization, but at that point I don't have `ParameterName` yet. Which means that I can only perform initialization that is global and doesn't depend on plugin configuration.

---

My suggestion here would be to introduce some kind of "init" hook, called after plugin instance construction but before any requests are served to the plugin instance. If applied to the example above, it could become something like this:
```golang
type Config struct {
    ParameterName `json:"parameter_name"`
    parameterValue string
    // Once is no longer necessary
}

// only called once per plugin instance
// assuming ParameterName is already unmarshalled here
func (c *Config) Init() {
    c.parameterValue = actuallyGetParameter(c.ParameterName)
}

func (c *Config) Access(kong *pdk.Pdk) {
  // simply use c.parameterValue
}
```

I also feel like some kind of shutdown hook could be useful. It could be used for things like flushing/closing files etc; for instance, the [current go-log example plugin](https://github.com/Kong/go-plugins/blob/726dd1342177f07319cb8954c74df97dcd4529ae/go-log.go) leaks file descriptors as far as I can tell.

**Comment by javierguerragiraldez** [comment]
you could do the parameter initialization in your Access method and then check if it's already set to avoid doing it twice.

**Comment by renato-zannon** [comment]
That's basically what I'm doing today, but that shifts the burden of initializing this resource to the first request(s).
In my case it's not an unacceptable delay, fortunately; however, I have a plugin that executes in <2ms on average, but then for the first request executes in >100ms.

What I'm wondering here is whether it would be possible to perform this initialization before the first request arrives

**Comment by javierguerragiraldez** [comment]
we've explicitly avoided to specify instance lifecycle to allow more flexibility in execution.  for example, currently each Kong worker initiates a separate connection with the external plugin, and keeps their own list of instances; but it could change to a shared resource, so a single instance could serve several workers.  Or, in the other direction, we could find better to spawn several instances and balance the load between them.  Besides, instances are closed on the Go side after some idle time, and Kong has to respawn a new one when needed.
As you can see, if we added an initialization phase, it would basically happen on the first request (or the first request handled by each worker, or the first request in a while), with the same end result as just doing it in the current phases.

**Comment by renato-zannon** [comment]
Thanks for the clarification, that makes sense! I'll close the issue then.
I guess I was implicitly assuming that the plugin was instantiated right when it is added to a route/service on Kong, not lazily.

I only have a related follow-up question: from your message I assume that (at least currently) the same plugin instance won't be handling two requests at the same time - which means that using synchronization primitives to modify instance-local properties (like caches) would be unnecessary. Is this something that can be relied upon long-term? Or would it be better to synchronize anyway, for forward compatibility?

**Comment by javierguerragiraldez** [comment]
>  I assume that (at least currently) the same plugin instance won't be handling two requests at the same time

no, that's not correct.  In the Lua side each worker handles several requests concurrently (can be many tens of thousands easily) by using coroutines.  In the Go side, it does the same with many Goroutines on each plugin instance, which can be handled by several threads to balance work among cores.

please, wrap any mutable shared state with synchronization primitives.

**Comment by jchenship** [comment]
> As you can see, if we added an initialization phase, it would basically happen on the first request (or the first request handled by each worker, or the first request in a while), with the same end result as just doing it in the current phases.

@javierguerragiraldez I have another scenario tho. I have a computed data structure is based on config, and this data structure is for more efficient access to the config values in the following requests. 

I mean I can save it to a global variable, but the problem is that I don't know when the config has changed and I need to reload the computed data structure. I mean I can re-serialize the config and store a checksum, but that's doing unnecessary work,  having a hook method for `StartInstance` is a better way than a global variable IMO.

**Comment by jchenship** [comment]
Actually scratch that, I if put the computed property in the Config struct, every time the config is reloaded, a new instance will be created with the new config string, so the computed property will be empty again. So I can simply based on whether that config field is empty to determine whether I need to initialize that computed field.

**Comment by renato-zannon** [comment]
@jchenship just keep in mind that multiple Config structs might be instantiated for the exact same config struct, so if it is paramount that you only compute this expensive initialization once, you'll need other kinds of storage.

In my case, I ended up using a global map (protected by a Mutex), where values are the result of the expensive initialization, and keys are JSON-ified config structs.

**Comment by jchenship** [comment]
@renato-zannon Thank you for the info. :+1: 

I think for my situation I'm ok for the computed field to be re-initialized from time to time, e.g. when config is changed (config auto reload is important for me), or kong decided to stop the instance after idling sometime and then restart it. I'm also using a mutex for initializing the computed property.

But using a global var definitely works as well.
