### ISSUE TITLE
panic: /usr/local/bin/go-pluginserver flag redefined: kong-prefix

### ISSUE THREAD

**Issue by BossKing-newbie** [Kong/go-pdk#80]
excuse me,I use the version of go:1.16 and go-pluginserver@v0.6.1 and go-pdk@v0.6.1,But there was a problem running the plugin.
![image](https://user-images.githubusercontent.com/54852330/147233224-00fb717f-ee77-40e1-abcd-5e9b766056b6.png)

**Comment by burntcarrot** [comment]
I guess you're developing the plugin with the help of the [official blog](https://konghq.com/blog/kong-gateway-go-plugin) by @mertingen.

I suspect this is due to the fact that the `Dockerfile` in the blog builds `go-pluginserver`, which also has a [`kong-prefix` flag](https://github.com/Kong/go-pluginserver/blob/master/main.go#L25).

**Comment by mertingen** [comment]
Thanks, @burntcarrot. It might be because it's more strict to protect the whole process from now on as I see. However, if we need to be sure, @BossKing-newbie may you share the details and code examples to reproduce the error?

**Comment by javierguerragiraldez** [comment]
hi @BossKing-newbie , could it be that you're using both go-pluginserver and the embedded server? (by importing "go-pdk/server")

Note that we're deprecating the go-pluginserver in favor of the embedded server, as the microserver-style is much better supported by the Go ecosystem.

**Comment by arun2205** [comment]
Hi @BossKing-newbie , I am also facing the same error, how did you fix it? below is the error I am facing. If you have fixed it can you please let me know :)
`/usr/local/bin/go-pluginserver flag redefined: kong-prefix
panic: /usr/local/bin/go-pluginserver flag redefined: kong-prefix

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000092180, {0x90f990, 0xc00037a2b0}, {0x7fbad96eedc0, 0xb}, {0x7fbad970f0b5, 0x4d})
        /usr/local/go/src/flag/flag.go:879 +0x2fa
flag.(*FlagSet).StringVar(...)
        /usr/local/go/src/flag/flag.go:762
flag.(*FlagSet).String(0x0, {0x7fbad96eedc0, 0xb}, {0x7fbad96f0ad4, 0xf}, {0x7fbad970f0b5, 0x4d})
        /usr/local/go/src/flag/flag.go:775 +0xae
flag.String(...)
        /usr/local/go/src/flag/flag.go:782
github.com/Kong/go-pdk/server.init()
        /root/go/pkg/mod/github.com/!kong/go-pdk@v0.6.1/server/server.go:26 +0x4c
plugin.open({0xc0000e8140, 0x3d})
        /usr/local/go/src/plugin/plugin_dlopen.go:102 +0x58a
plugin.Open(...)
        /usr/local/go/src/plugin/plugin.go:32
main.(*PluginServer).loadPlugin(0xc000094280, {0x7fffd3a82410, 0x5f5868})
        /root/go/pkg/mod/github.com/!kong/go-pluginserver@v0.6.1/pluginserver.go:123 +0x1c5
main.(*PluginServer).GetPluginInfo(0xc000092180, {0x7fffd3a82410, 0x8}, 0xc00035fe60)
        /root/go/pkg/mod/github.com/!kong/go-pluginserver@v0.6.1/pluginserver.go:239 +0x65
main.dumpInfo()
        /root/go/pkg/mod/github.com/!kong/go-pluginserver@v0.6.1/main.go:52 +0x6b
main.main()
        /root/go/pkg/mod/github.com/!kong/go-pluginserver@v0.6.1/main.go:142 +0x45`

**Comment by gszr** [comment]
@arun2205,

As suggested by Javier, please ensure you are using the "embedded server" approach, as documented [here](https://docs.konghq.com/gateway/latest/plugin-development/pluginserver/go/). The external go-pluginserver is long deprecated and removed as of Kong 3.0.0.

Please open a new issue if the issue persists with the embedded server approach.

Happy Konging 🦍
