### ISSUE TITLE
How to read cookies  ？

### ISSUE THREAD

**Issue by yaobo-lab** [Kong/go-pdk#81]
When I was developing a go plugin. How to read cookies?

**Comment by yaobo-lab** [comment]
i got it

**Comment by Alihvs** [comment]
@yaobo-lab
How did you solve this?
Getting and setting the cookie.

**Comment by chithanh12** [comment]
Hi @yaobo-lab, 
I have the same question. Can you share your solution with us?

**Comment by chithanh12** [comment]
I found a solution:

`func (config Config) Access(kong *pdk.PDK) {
	cookieHeader, _ := kong.Request.GetHeader("cookie")
	cookies := getCookies(cookieHeader)
	tmp, _ := json.MarshalIndent(cookies, "", "  ")

	kong.Log.Info(fmt.Sprintf("Cookies hehehehe :%v", string(tmp)))
}

// You can return as []*Cookies if you want
func getCookies(cookieHeaderValue string) map[string]string {
	if cookieHeaderValue == "" {
		return map[string]string{}
	}

	header := http.Header{}
	header.Add("Cookie", cookieHeaderValue)
	request := http.Request{Header: header}
	rs := map[string]string{}
	for _, c := range request.Cookies() {
		rs[c.Name] = c.Value
	}
	return rs
}

`
