### ISSUE TITLE
Response.ExitStatus causes 500 in kong: plugin_servers/pb_rpc.lua:45: attempt to index local 'v' (a nil value)

### ISSUE THREAD

**Issue by diefans** [Kong/go-pdk#83]
If I use `ExitStatus(http.StatusFound)` I get a `500` and 
```
plugin_servers/pb_rpc.lua:45: attempt to index local 'v' (a nil value)
```
If I use `Exit(http.StatusFound, "", nil)` everything is ok.

While inspecting the code, I would guess from the lua error, that the rpc call is missing some values.
IMHO I would just call `Exit` from `ExitStatus` with empty values for `body` and `headers`

Also setting the headers in `Exit` seems not to work - I had to use `SetHeader` to create a "working" `302`.

**Comment by diefans** [comment]
my kong version is 2.7.0

**Comment by javierguerragiraldez** [comment]
thanks for the report, will try to reproduce
