### ISSUE TITLE
kong.Request.GetRawBody() is empty, if body is buffered into temporary file on behalf of nginx/kong

### ISSUE THREAD

**Issue by diefans** [Kong/go-pdk#85]
I want to make a POST request to a plugin whose body size exceeds the default body size (http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size) of nginx.

 `kong.Request.GetRawBody()` return an empty body if it is buffered, e.g.:
```
a client request body is buffered to a temporary file /usr/local/kong/client_body_temp/0000000001
```

If I increase the body size of nginx/kong
```
KONG_NGINX_PROXY_CLIENT_BODY_BUFFER_SIZE: 32k
```
I get the body via `kong.Request.GetRawBody()`

**Comment by diefans** [comment]
I am using `go-pdk == v0.7.1` and `kong == 2.7.0`

**Comment by sec23206** [comment]
I know this isn't the answer to your question, but I was previously experimenting with the JS PDK to write a plugin which transformed the response coming back from the service.  A comment in the source code for the PDK's version of kong.service.response.getRawBody() and .getBody() indicated that you needed to call kong.service.request.enable_buffering() during an earlier phase.  It almost seems like the Go PDK needs an option to turn *off* buffering on the request so the plugin code has access to the entire request payload.
