### ISSUE TITLE
Supported Go versions

### ISSUE THREAD

**Issue by phclark** [Kong/go-pdk#86]
Are there any plans to update the supported Go versions? You're still running on Go version 1.13, which is over 2 years old at this point and has a number of security vulnerabilities.

**Comment by mayocream** [comment]
I think there's no reason to stop us from upgrading Go to 1.17. 🤔

**Comment by javierguerragiraldez** [comment]
i agree, Go has a very good compatibility record.  on the other hand, since the go-pluginserver is deprecated, there shouldn't be any difference for the plugin developers, as you can use whatever version you wish.  each plugin is an independent executable and could be built with different versions.

**Comment by gszr** [comment]
We are by now using Go 1.18. Closing this issue
