### ISSUE TITLE
Mutate response body

### ISSUE THREAD

**Issue by nenad-lambdas** [Kong/go-pdk#92]
We are writing a go plugin to transform the body of the response, we can obtain the body via `kong.ServiceResponse.GetRawBody()` but it seems we have no way of setting the response body?

**Comment by javierguerragiraldez** [comment]
the `ServiceResponse` is what you get from the target, you can't modify it.  But you can definitely change what it's sent back to the client with the <body> argument of `kong.Response.Exit()`

**Comment by gszr** [comment]
Please open a Discussion in [Kong/kong/discussions](https://github.com/Kong/kong/discussions) if you have more questions!
