### ISSUE TITLE
Proposal: add service request path forecast

### ISSUE THREAD

**Issue by rhzs** [Kong/go-pdk#94]
Hi Kong GO-PDK Team,

**Context**
I have a use case where I need to built custom plugin depends on the original service request path. 

**Current Condition**
Right now, I don't think it is possible, I don't see any useeful function in Go PDK.

**My Solution**
I wrote a function to determine service request path, as follow:

```go
func servicePath(kong *pdk.PDK) string {
	path, _ := kong.Request.GetPath()
	route, _ := kong.Router.GetRoute()

	svcPath := path

	if route.StripPath {
		kongSvc, _ := kong.Router.GetService()
		svcPath = kongSvc.Path

                // TODO: see on all paths
		tailReqPath := strings.Replace(path, route.Paths[0], "", 1)

		svcPath += tailReqPath
	}

	_ = kong.Log.Debug("svcPath: ", svcPath, ", path: ", path, ", route path", route.Paths[0])

	return svcPath
}
```

My above solution still lacks 2/3 things:
1. Path iteration
2. Route versioning
3. Other things that I don't know.. 

Would it possible if we could add something like what the above function does? If not possible, what's the alternative? My above solution feels hacky to me, I don't know if that's the right thing to do it in Kong Plugin. 

Thank You!

**Comment by fffonion** [comment]
@rhzs You can read `kong.Nginx.GetVar["upstream_uri"]` after rewrite phase to get the service request path.

**Comment by rhzs** [comment]
@fffonion any working example?

**Comment by gszr** [comment]
This forum is reserved for bug reports; please start a discussion in [Kong/kong/discussions](https://github.com/Kong/kong/discussions) if you have specific questions!
