### ISSUE TITLE
How to load custom go plugins in Kubernetes with size more than 1MB?

### ISSUE THREAD

**Issue by akashjain971** [Kong/go-pdk#97]
I was trying out custom golang kong plugins from the sample [here](https://github.com/Kong/go-plugins/blob/master/go-hello.go).
The binary is 9.5MB in size which is way above the Kubernetes configmap size of 1MB. What is the right way to load big custom plugins in Kubernetes?

**Comment by rhzs** [comment]
@akashjain971 you may want to build your own Kong image that contains your own plugin. This works perfectly in my case.

**Comment by gszr** [comment]
For questions, please use the discussions forum in https://github.com/Kong/kong/discussions.
